### ISSUE TITLE
linux 4.4 proposal

### ISSUE THREAD

**Issue by wongsyrone** [dolohow/uksm#1]
Hi,

Thanks for your effort to get this work on modern kernels. I successfully compiled and tested on Linux 4.4.13 running on LEDE WRT1900ac router, it seems all works well until now.

My modification is based on your uksm-4.6.patch, the details as follow:
- changed several function signatures e.g. removed all `, false`
- changed "unsigned long *src = s1;" in is_full_zero() to "const unsigned long *src = s1;"
  which makes GCC happier

You can check the patch [here](https://github.com/wongsyrone/lede-1/blob/master/target/linux/generic/patches-4.4/999-01-add-uksm.patch), you may need to adjust the patch offset via quilt or by hand.

**Comment by dolohow** [comment]
Hi,

Thank you for paying interest in this project.  I am trying to create those patches with the lowest possible effort and to not diverge from upstream.  Yet your changes are very simple and I would probably incorporate them soon.  I am wondering how do I miss those warnings.

Happy coding :)
Łukasz

**Comment by wongsyrone** [comment]
Thanks. I'm closing this.
