### ISSUE TITLE
Can't use the patch for 4.9. Would you recreate it?

### ISSUE THREAD

**Issue by DrReD** [dolohow/uksm#12]
I'm trying to patch a 4.9.8 Kernel, but when I try to use the uksm patch, git does not like it. At first it bitches about some extra spaces here and there, then after I removed all of them, git still says it cannot recognize the patch format. Apparently it has something to do with the patch not being generated within git or not being in the proper "email format" that git is expecting (i do not know much about git - I just googled the error message) and the suggestion they give on most blogs is to ask the upstream to please regenerate the patch with git, which should probably fix any format problem. So Here I am asking... :)
Would you be so kind to regenerate the patch (or to let me know how to properly handle it)?

**Comment by naixia** [comment]
What command did you use?  git am ? or patch -p1 < patchfile ?
The files in this repo are pure diff results. Please apply by "patch" command.
