### ISSUE TITLE
Support kernel 4.10.x

### ISSUE THREAD

**Issue by tpgxyz** [dolohow/uksm#13]
Hi,

Looks like your latest patch uksm-0.1.2.5-for-v4.9.1+.patch does not apply to kernel-4.10
Logs for kernel build can be found here:
https://abf.openmandriva.org/build_lists/98142

Is there any ETA for a updated patch ?

**Comment by dolohow** [comment]
I will try to port today, but I might actually do that tomorrow.  Unless @naixia is going to be faster :)

**Comment by naixia** [comment]
@dolohow I am out of office for a few days, thank you for your help :+1:

**Comment by dolohow** [comment]
Fixed in c13722d723cf6022e2e4e6bad2685ff6cc3e3d68

**Comment by tpgxyz** [comment]
Thanks, patch applies cleanly.
Please add credits to www.openmandriva.org a distribution that uses UKSM for ages ;)

**Comment by naixia** [comment]
@tpgxyz I'am glad to hear that!
I'll someday collect a list of linux distributions that can/may use UKSM including openmandriva and put it on the readme page ;-)
