### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by javashin** [dolohow/uksm#15]
Can You make uksm 1.2.6 updated patch for the kernel 3.16+ 3.16.42 the recent one since this kernel its LTS and EOL is on 2020 . please . if is possible .

Thanks in advance .

**Comment by javashin** [comment]
the old one 1.2.3 dont apply to the recent one 3.16.42

**Comment by naixia** [comment]
@javashin Currently I have no plan/time to support 3.x kernels. However, as always, any effort from others is welcome.

**Comment by javashin** [comment]
since this i been using the kernel 4.4 which is working fine until today i tried to hibernate and i used the last uksm patch and when i try to resume from hibernation results that i cant the system dont resume at all without the uksm patch the system resumes without no problems

**Comment by naixia** [comment]
@javashin Well, the hibernation/resume is a nasty beast. My personal machine never hibernate and resume properly even with official kernels. So any further information like dmesg or error message that can help to pinpoint the bug?

**Comment by dolohow** [comment]
I agree, suspend is very, very tricky.  Every second kernel release my machine won't wake up from suspend and it is not due to uksm.  You can try netconsole to get some info of what is going on.  Closing for now.
