### ISSUE TITLE
Update Request: Kernel 4.11

### ISSUE THREAD

**Issue by jyhi** [dolohow/uksm#17]
It's been a long time since the release of Linux Kernel 4.11. Doesn't UKSM have a plan to port to 4.11?

**Comment by dolohow** [comment]
I will port tomorrow

**Comment by Alois-DE** [comment]
Czekamy na nową wersję :)

**Comment by dolohow** [comment]
Fixed in https://github.com/dolohow/uksm/commit/1c5a0ace950f786f2d306173532f5d27d1dc01a5
