### ISSUE TITLE
Update Request: Kernel 4.12

### ISSUE THREAD

**Issue by jyhi** [dolohow/uksm#21]
Kernel version 4.12 was released on 2017-07-02.

I suggest UKSM always follow the next mainline kernel's release candidate (-rc) so that when new kernel releases UKSM can quickly keep up with upstream.

**Comment by naixia** [comment]
The port to 4.12 is now done.  I'll try to release the new ports as early as possible next time. ;-)

**Comment by kernelOfTruth** [comment]
@naixia awesome ! Thank you :)
