### ISSUE TITLE
Patch not compatibility with 4.14.

### ISSUE THREAD

**Issue by drdeimos** [dolohow/uksm#27]
If i try apply latest 4.13 patch apply to 4.14 kernel get some errors.
I know that this is wrong, but I would like a patch adapted for 4.14.
Thank you for you work.

https://pastebin.com/xLFAzSt6

**Comment by joksik** [comment]
confirm. waiting for new release

**Comment by dolohow** [comment]
6061f44cc0f8edb832a00d6d69966d000b16acf2
