### ISSUE TITLE
UKSM is now a paper from FAST '18

### ISSUE THREAD

**Issue by asherliu** [dolohow/uksm#28]
Dear Lukasz,

Sorry for putting this communication message (non-issue) in issue tab since I didn't get a way to connect you.

First off, thank you very much for spending tremendous efforts maintaining the UKSM patch for Nai Xia. Recently, we have, very fortunately, published "UKSM: Swift Memory Deduplication via Hierarchical and Adaptive Memory Region Distilling" as a paper in FAST '18, along with our slides you can find here: https://www.usenix.org/conference/fast18/presentation/xia.

For the purpose of ease of understanding and extending the impacts of this project, would you please add those information in the README.md of this repository?

Thanks,
-------
Hang Liu, Ph.D.,
Assistant Professor,
University of Massachusetts Lowell

**Comment by dolohow** [comment]
Hi,

Thank you for interest in UKSM.  Can you please make a Pull Request?

**Comment by dolohow** [comment]
Merged in #29
