### ISSUE TITLE
how to submit memory area to KSM

### ISSUE THREAD

**Issue by chr1shung** [dolohow/uksm#30]
sorry a bit irrelevant to the project
I'm currently doing an experiment to see the effectiveness of KSM on Docker container
and you mention that user had to submit memory area to vanilla KSM manually 
just curious how can I do that ?

**Comment by demfloro** [comment]
MADV_MERGEABLE flag of [madvise() syscall](http://man7.org/linux/man-pages/man2/madvise.2.html).
