### ISSUE TITLE
deduplication results worse than vanilla ksm

### ISSUE THREAD

**Issue by chr1shung** [dolohow/uksm#33]
I patched uksm on my Linux 4.9 kernel, comparing it with the original ksm,  and the result isn't quite satisfying.
below is the simple experiment I did, I use `vagrant` to launch 4VM at first, and then launch 4 more VMs at like 100s.
![Imgur](https://i.imgur.com/07aZfDk.png)
It seems uksm couldn't find more page to share after 100s.  
I realize there's some additional parameter on uksm, just wondering which one I need to tune in order to make the result better ?  

thanks for the help.

**Comment by dolohow** [comment]
Thank you for your interest in `UKSM`.

What is the method of your measurements?

How much RAM do you have?

Also checkout `/sys/kernel/mm/uksm/fully_scanned_round`.

You can do:
`for file in /sys/kernel/mm/uksm/* ; do echo $file; cat $file ; done`
and paste it here

Also what is your CPU utilization?  If it's high, then uksm will not scan any pages.

Wait few minutes when all VMs are up and then check RAM utlization.

**Comment by chr1shung** [comment]
I use `free -m | grep Mem | awk '{print $3}'` to get the memory usage of the system. (I have 16G RAM)
here's the info in `/sys/kernel/mm/uskm` of launching 4VMs and wait for like 10 mins:
```
/sys/kernel/mm/uksm/abundant_threshold
10
/sys/kernel/mm/uksm/cpu_governor
[full] medium low quiet
/sys/kernel/mm/uksm/cpu_ratios
20 40 MAX/4 MAX/1
/sys/kernel/mm/uksm/ema_per_page_time
3039
/sys/kernel/mm/uksm/eval_intervals
1000 500 200 50
/sys/kernel/mm/uksm/full_scans
8
/sys/kernel/mm/uksm/hash_strength
49
/sys/kernel/mm/uksm/max_cpu_percentage
95
/sys/kernel/mm/uksm/pages_scanned
332117
/sys/kernel/mm/uksm/pages_shared
5110
/sys/kernel/mm/uksm/pages_sharing
17308
/sys/kernel/mm/uksm/pages_unshared
73876
/sys/kernel/mm/uksm/run
1
/sys/kernel/mm/uksm/sleep_millisecs
20
/sys/kernel/mm/uksm/sleep_times
6522
/sys/kernel/mm/uksm/thrash_threshold
50
```

the `pages_sharing` is quite low compared to vanilla ksm (which can get ~150000 pages_sharing)
also I didn't see high CPU usage during the experiment.

**Comment by dolohow** [comment]
UKSM handles also zero pages separately, can you check `/proc/meminfo` `KsmZero` property? And add `pages_sharing` to `KsmZero`

**Comment by chr1shung** [comment]
I check the `KsmZero` property, it's around 85000kB and combining with `pages_sharing`(which is ~17000) we can get like 150MB memory saving.
Still less than vanilla KSM which saves ~700MB.

**Comment by dolohow** [comment]
Can you check kernel 4.4 for example?  Also on your graph it seems that uksm and ksm are at the same memory consumption level after some time (not sure how much since there is no data on x-axis.

Also there were some tests conducted[1] 8.2.1 and conslusion is uksm outperformed ksm when it comes to memory usage and cpu in VM test.

https://www.usenix.org/system/files/conference/fast18/fast18-xia.pdf

**Comment by chr1shung** [comment]
Do you mean patch uksm on kernel4.4?  actually I've tried it at the first time but there's a FAIL while pathing it. ( kernel version 4.4.133)
```
patching file Documentation/vm/00-INDEX
patching file Documentation/vm/uksm.txt
patching file fs/exec.c
Hunk #2 succeeded at 1205 (offset 21 lines).
patching file fs/proc/meminfo.c
Hunk #1 succeeded at 118 (offset -3 lines).
Hunk #2 succeeded at 179 (offset -3 lines).
patching file include/asm-generic/pgtable.h
patching file include/linux/ksm.h
patching file include/linux/mm_types.h
patching file include/linux/mmzone.h
Hunk #1 succeeded at 158 (offset 1 line).
Hunk #2 succeeded at 815 (offset 3 lines).
patching file include/linux/sradix-tree.h
patching file include/linux/uksm.h
patching file kernel/fork.c
Hunk #1 succeeded at 452 (offset 7 lines).
Hunk #2 succeeded at 505 (offset 7 lines).
patching file lib/Makefile
patching file lib/sradix-tree.c
patching file mm/Kconfig
patching file mm/Makefile
patching file mm/memory.c
Hunk #4 succeeded at 1180 (offset 1 line).
Hunk #5 succeeded at 2016 with fuzz 1 (offset 1 line).
Hunk #6 succeeded at 2164 (offset 16 lines).
Hunk #7 succeeded at 2189 (offset 16 lines).
patching file mm/mmap.c
Hunk #3 succeeded at 754 (offset 14 lines).
Hunk #4 succeeded at 857 (offset 14 lines).
Hunk #5 FAILED at 914.
Hunk #6 succeeded at 1340 (offset 14 lines).
Hunk #7 succeeded at 1683 (offset 14 lines).
Hunk #8 succeeded at 1725 (offset 14 lines).
Hunk #9 succeeded at 2545 (offset 36 lines).
Hunk #10 succeeded at 2807 (offset 36 lines).
Hunk #11 succeeded at 2865 (offset 36 lines).
Hunk #12 succeeded at 2901 (offset 36 lines).
Hunk #13 succeeded at 2942 (offset 36 lines).
Hunk #14 succeeded at 3056 (offset 36 lines).
Hunk #15 succeeded at 3162 (offset 36 lines).
1 out of 15 hunks FAILED -- saving rejects to file mm/mmap.c.rej
patching file mm/rmap.c
Hunk #1 succeeded at 1093 (offset 22 lines).
patching file mm/uksm.c
patching file mm/vmstat.c
Hunk #1 succeeded at 763 (offset 1 line).
```

I actually tried to replicate Figure. 9-(c) in the paper to check whether uksm outperformed ksm in terms of deduplication spped.

**Comment by dolohow** [comment]
Try 4.4.70.  Perhaps we should update patch for newer versions?

**Comment by chr1shung** [comment]
The patch file works well on 4.4.70 .  But the deduplication result is the same as 4.9 which saved about ~100MB memory.

**Comment by MGAndreasen** [comment]
Any news regarding this?

**Comment by naixia** [comment]
We have disscused some similar problems in closed issues. pages_sharing is NOT accurate. Please benchmark with actual used/free anonymous pages like we did in the FAST18 paper Nai Xia 邮箱：nai.xia@gmail.com 签名由 网易邮箱大师 定制 On 07/09/2018 17:32, Michael Gerner Andreasen wrote: Any news regarding this? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xCuri0** [comment]
@naixia how can we see those ?

**Comment by soredake** [comment]
https://www.usenix.org/system/files/conference/fast18/fast18-xia.pdf
