### ISSUE TITLE
4.18 ?

### ISSUE THREAD

**Issue by xCuri0** [dolohow/uksm#36]
When will you release 4.18 patch ?

**Comment by dolohow** [comment]
I'll try today.

**Comment by Szpadel** [comment]
Maybe #35 is useful?

**Comment by xCuri0** [comment]
I managed to fix the conflicts but I'm getting some error related to missing firmware when building so I can't test

**Comment by dolohow** [comment]
I pushed 4.18, please go out and test and sorry for late update.
