### ISSUE TITLE
I am 

### ISSUE THREAD

**Issue by naixia** [dolohow/uksm#45]
I have been sick for quite some time and unable to maintain this project anymore.
I hope someone can take it over with the information in our academic paper at the bottom of the README.

**Comment by dragetd** [comment]
This is very sad to hear. Get well soon!

Sadly I have too little kernel hacking experience and would not be able to properly review PRs :/

[edit] I'll happily build a test-pipeline that tries to apply the patches to all corresponding kernel sources and also future ones and maybe tries qemu booting them! The queston is just when I will get to it xD

**Comment by Szpadel** [comment]
I trying to maintain compatibility of this patch with newer kernel releases here: 
https://github.com/Szpadel/fedora-uksm/blob/master/0002-Add-UKSM.patch

I can contribute here back with updated patches when I figure out how to port it to newer version.
Note: I'm using my build daily, so I have high confidence in working state of the patch.

**Comment by dolohow** [comment]
@Szpadel testing and patches are always welcome :)
