### ISSUE TITLE
What do you think about supporting NUMA-awared uksm  ?

### ISSUE THREAD

**Issue by colo-ft** [dolohow/uksm#5]
Hi,

I opened a new issue here ;)
I noticed that ksm supports to merge pages in the range of their NUMA nodes.
(You can use the sysfs /sys/kernel/mm/ksm/merge_across_nodes parameter to control merging of pages across different NUMA nodes.)

How about uksm ?  Are you going to support it ? Does it make any sense ?

Thanks.

**Comment by naixia** [comment]
If you search linux-mm you will find my comment on this ksm feature years ago. 
It's not a perfect solution yet. It makes some sense, but maybe to big players only. 
It takes much more effort  to be perfect. I have no plan to support this yet.

**Comment by colo-ft** [comment]
Got it, :+1:  thanks for your reply, then, I'll close this issue.
