### ISSUE TITLE
README link to project website fails

### ISSUE THREAD

**Issue by polarathene** [dolohow/uksm#54]
The link points to http://kerneldedup.org/

As the original maintainer of the project has stepped down, did they also stop running that website? 

Would it be better to use github.io or netlify, both free static site services. Or is the website just temporarily down?

**Comment by JohnyPeaN** [comment]
I would say its permanently down. Have been checking sporadically for news and haven't seen it online for about 2 years. web.archive confirms it:

[http://web.archive.org/web/2017*/kerneldedup.org](http://web.archive.org/web/2017*/kerneldedup.org)

**Comment by dolohow** [comment]
I removed website from README and patches https://github.com/dolohow/uksm/commit/72836c5d30fa6c4fdb71d833a05d8e5f6fe4e280.
