### ISSUE TITLE
Linux Kernel 5.6.5 pathing FAILED

### ISSUE THREAD

**Issue by HougeLangley** [dolohow/uksm#59]
patching file Documentation/vm/uksm.txt
patching file fs/exec.c
Hunk #2 FAILED at 1388.
1 out of 2 hunks FAILED -- saving rejects to file fs/exec.c.rej
patching file fs/proc/meminfo.c
patching file include/asm-generic/pgtable.h
patching file include/linux/ksm.h
patching file include/linux/mm_types.h
Hunk #1 succeeded at 361 (offset 3 lines).
patching file include/linux/mmzone.h
patching file include/linux/sradix-tree.h
patching file include/linux/uksm.h
patching file kernel/fork.c
Hunk #1 succeeded at 604 (offset 6 lines).
patching file lib/Makefile
patching file lib/sradix-tree.c
patching file mm/Kconfig
patching file mm/Makefile
patching file mm/ksm.c
patching file mm/memory.c
patching file mm/mmap.c
patching file mm/uksm.c
patching file mm/vmstat.c
Hunk #1 succeeded at 1179 (offset 10 lines).

**Comment by arvin-foroutan** [comment]
Ran into the same problem. If you want a quick fix until the new patch is released, you can do the following:

change line 83 in uksm-5.6.patch 

from:

`
current->self_exec_id++;`

to:

`WRITE_ONCE(current->self_exec_id, current->self_exec_id + 1);`

**Comment by sirlucjan** [comment]
https://gitlab.com/sirlucjan/kernel-patches/-/blob/master/5.6/uksm-patches/0001-UKSM-for-5.6.patch

**Comment by firasuke** [comment]
Can confirm that @sirlucjan 's version of the patch is working with kernel version 5.6.6.

EDIT: Also working with 5.6.11.
