### ISSUE TITLE
How to install uksm on CENT OS 6.7

### ISSUE THREAD

**Issue by zhugf** [dolohow/uksm#6]
Hi,

To reduce qemu memory footprint, I want to install uksm on a CENT OS 6.7 host, the kernel version is:
2.6.32-642.11.1.el6.x86_64. For some reason, I can't upgrade CENT OS to 7 or higher.

Could you please tell me how to install or patch kernel?

thank you so much.

**Comment by naixia** [comment]
You can google out a lot of links on how to patch and build a CENTOS/RHEL kernel from source.
However, currently, uksm patches are only for vanilla kernels. 
You can port it to rhel kernels if you like but I don't think this job is trivial. 
I myself have no plan to do this by now, sorry.
