### ISSUE TITLE
uksm patches for 5.7 fail on 5.8-rc2

### ISSUE THREAD

**Issue by gottaeat** [dolohow/uksm#64]
it seems like `include/asm-generic/pgtable.h` got split into:
`./include/asm-generic/pgtable-nop4d.h`
`./include/asm-generic/pgtable-nopmd.h`
`./include/asm-generic/pgtable-nopud.h`
`./include/asm-generic/pgtable_uffd.h`
and causes patch to fail when it can't find it.
also `fs/proc/meminfo.c` and `mm/memory.c` keeps the rest of the patch from being cleanly applied.

**Comment by JohnyPeaN** [comment]
Hi, I modified the 5.7 patch for 5.8 changes in rc1. It works for me on 2 machines without problems so far.

here is complete patch:
https://pastebin.com/2nSW624B

**Comment by dolohow** [comment]
Fixed in da2ad770c9a1ed1c8e54e544941df359d75adc92

For the future, I do not tinker around `-rc` versions.
