### ISSUE TITLE
Please add support for linux-5.15

### ISSUE THREAD

**Issue by bhzhu203** [dolohow/uksm#73]
Please add support for linux-5.15 , it is released. Thanks
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.tar.xz

**Comment by MoisesMH** [comment]
Yes, please! 5.15.2 is out and we'd like to experience the advantages uksm offers.

**Comment by pfactum** [comment]
Anyone compared this with https://gitlab.com/post-factum/pf-kernel/-/commits/ksm-5.15/ + https://gitlab.com/post-factum/uksmd ?

**Comment by MoisesMH** [comment]
Actually I didn't know about userspace ksm daemon. Maybe I'll look deeper then hehe.
Well I've found a rebase of uksm for 5.15 from kernel-sirlucjan patches:

https://github.com/sirlucjan/kernel-patches/tree/master/5.15/uksm-patches

N-joy haha

**Comment by bhzhu203** [comment]
> Yes, please! 5.15.2 is out and we'd like to experience the advantages uksm offers.

I find that uksm-5.14.patch can be used in 5.15.0

**Comment by dolohow** [comment]
Released in c806b3b
