### ISSUE TITLE
Please add support for linux-5.16

### ISSUE THREAD

**Issue by ruslanvkarmanov** [dolohow/uksm#75]
Rejected part of mm/ksm.c:

--- mm/ksm.c
+++ mm/ksm.c
@@ -852,17 +852,6 @@ static int unmerge_ksm_pages(struct vm_area_struct *vma,
        return err;
 }

\-static inline struct stable_node *page_stable_node(struct page *page)
\-{
\-       return PageKsm(page) ? page_rmapping(page) : NULL;
\-}
\-
\-static inline void set_page_stable_node(struct page *page,
\-                                       struct stable_node *stable_node)
\-{
\-       page->mapping = (void *)((unsigned long)stable_node | PAGE_MAPPING_KSM);
\-}
\-
\#ifdef CONFIG_SYSFS
\/*
  \* Only called through the sysfs control interface:

**Comment by sirlucjan** [comment]
Please look at #77

**Comment by ruslanvkarmanov** [comment]
Thanks!
