### ISSUE TITLE
CPU Process HOG when more than 15 same KVM guest...

### ISSUE THREAD

**Issue by eczema** [dolohow/uksm#9]
Hi,

We are facing a issue regarding uksm usage...
Even if it work very well, kvm seems unable to works correctly over a certain number of same nodes.

In our test we use 20 identical guests ( 3G of ram each )  using kvm 2.4.x with VT enabled and we observe that guest get cpu usage up to 100%. With enough memory and uksm disabled all runs well...

So question: is there a way to keep uksm running but discard specific PID from uksm memory management ? 

Thx for your lights..... 

Alain

**Comment by naixia** [comment]
Well, I can do nothing with your limited information. I personally run up to 40+ kvm guests without a problem.

I need more detailed information about your issue. e.g. The details of your setup and benchmarks, which process or system behavior consumes the CPU when the guest CPU gets 100%? any memory overcommit?

I's not hard to implement that feature you request. However, I want to know why it's really needed.

**Comment by fallenfuzz** [comment]
Hey @naixia , any ETA for adding the code from colo-ft?

**Comment by naixia** [comment]
@CJloHuK in 3~4 days, I am working on it.

**Comment by naixia** [comment]
@CJloHuK I am lucky to have time and have done it today, please checkout and test the new release ;-)

**Comment by naixia** [comment]
Well, since no further information can be gotten for this issuse, I am closing it.

**Comment by fallenfuzz** [comment]
Thanks @naixia :+1: 
we'll check that and let you know, hopefully soon enough :)
